name: pavucontrol-qt AppImage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 16 1/7 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: build
      run: |
        sudo apt update
        sudo apt install libfuse2 pavucontrol-qt
        sudo apt install ninja-build autotools-dev autoconf automake build-essential meson cmake
        wget https://raw.githubusercontent.com/Samueru-sama/pavucontrol-qt-AppImage/main/debian-pavucontrol-qt-AppImage.sh
        chmod a+x ./debian-pavucontrol-qt-AppImage.sh
        ./debian-pavucontrol-qt-AppImage.sh
        mkdir dist
        mv *AppImage dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pavucontrol-qt-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4
          with:
            name: pavucontrol-qt-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: |
              *.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
